name: project_z
description: "Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.1.0
  provider: ^6.1.2
  fpdart: ^1.1.1
  auto_route: ^9.3.0+1
  equatable: ^2.0.7
  dev: ^1.0.0
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  logger: ^2.5.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  mocktail: ^1.0.4
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  mask_text_input_formatter: ^2.9.0

  #build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true

  assets:
     - assets/mock/news/
     - assets/mock/categories/
     - assets/mock/products/
     - assets/footer/
     - assets/icons/
     - assets/basket/
     - assets/order/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/icons.ttf
    - family: Neometric
      fonts:
        - asset: assets/fonts/neometric/Neometric Alt Black (Regular).otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric Alt Black Italic (Bold Italic).otf
          weight: 900
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Bold (Regular).otf
          weight: 700
        - asset: assets/fonts/neometric/Neometric Alt Bold Italic (Bold Italic).otf
          weight: 700
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Extra Bold (Bold).otf
          weight: 800
        - asset: assets/fonts/neometric/Neometric Alt Extra Bold Italic (Bold Italic).otf
          weight: 800
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Extra Light (Regular).otf
          weight: 200
        - asset: assets/fonts/neometric/Neometric Alt ExtraLight Italic (Italic).otf
          weight: 200
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Hairline (Regular).otf
          weight: 100
        - asset: assets/fonts/neometric/Neometric Alt Hairline Italic (Italic).otf
          weight: 100
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Heavy (Bold).otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric Alt Heavy Italic (Bold Italic).otf
          weight: 900
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Italic (Italic).otf
          weight: 400
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Light (Regular).otf
          weight: 300
        - asset: assets/fonts/neometric/Neometric Alt Light Italic (Italic).otf
          weight: 300
          style: italic
        - asset: assets/fonts/neometric/Neometric Alt Medium (Regular).otf
          weight: 500
        - asset: assets/fonts/neometric/Neometric Alt Medium Italic (Italic).otf
          weight: 500
          style: italic
        - asset: assets/fonts/neometric/Neometric Black (Regular).otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric Black Italic (Bold Italic).otf
          weight: 900
          style: italic
        - asset: assets/fonts/neometric/Neometric Bold Italic (Bold Italic).otf
          weight: 700
          style: italic
        - asset: assets/fonts/neometric/Neometric Extra Bold (Bold).otf
          weight: 800
        - asset: assets/fonts/neometric/Neometric Extra Bold Italic (Bold Italic).otf
          weight: 800
          style: italic
        - asset: assets/fonts/neometric/Neometric Extra Light (Regular).otf
          weight: 200
        - asset: assets/fonts/neometric/Neometric Extra Light Italic (Italic).otf
          weight: 200
          style: italic
        - asset: assets/fonts/neometric/Neometric Hairline (Regular).otf
          weight: 100
        - asset: assets/fonts/neometric/Neometric Hairline Italic (Italic).otf
          weight: 100
          style: italic
        - asset: assets/fonts/neometric/Neometric Heavy (Bold).otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric Heavy Italic (Bold Italic).otf
          weight: 900
          style: italic
        - asset: assets/fonts/neometric/Neometric Italic (Italic).otf
          weight: 400
          style: italic
        - asset: assets/fonts/neometric/Neometric Light (Regular).otf
          weight: 300
        - asset: assets/fonts/neometric/Neometric Light Italic (Italic).otf
          weight: 300
          style: italic
        - asset: assets/fonts/neometric/Neometric Medium (Regular).otf
          weight: 500
        - asset: assets/fonts/neometric/Neometric Medium Italic (Italic).otf
          weight: 500
          style: italic
        - asset: assets/fonts/neometric/Neometric-AltRegular.otf
          weight: 400
        - asset: assets/fonts/neometric/Neometric-Regular.otf
          weight: 400
        - asset: assets/fonts/neometric/Unnamed Bold (Regular).otf
          weight: 700
