name: project_z
description: "Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Основные зависимости
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Локальные пакеты
  shop_domain:
    path: ../packages/domain/shop_domain
  shop_hive:
    path: ../packages/data/local/shop_hive
  shop_network:
    path: ../packages/data/network/shop_network

  # Управление состоянием
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  provider: ^6.1.2

  # Навигация
  auto_route: ^9.3.0+1

  # UI компоненты
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  mask_text_input_formatter: ^2.9.0

  # Утилиты и инструменты
  fpdart: ^1.1.1
  equatable: ^2.0.7
  freezed: ^2.5.7
  logger: ^2.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  rxdart: ^0.28.0
  intl: any
  flutter_gen: ^5.10.0
  hive_flutter: ^1.1.0

# Зависимости для разработки
dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.4.5
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2

# Flutter конфигурация
flutter:
  uses-material-design: true
  generate: true

  # Ресурсы приложения
  assets:
    - assets/app_bar/
    - assets/mock/
    - assets/mock/news/
    - assets/mock/categories/
    - assets/mock/products/
    - assets/footer/
    - assets/icons/
    - assets/basket/
    - assets/order/
    - assets/search/
    - assets/authentication/

  # Конфигурация шрифтов
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/icons.ttf

    - family: Neometric
      fonts:
        # Regular styles
        - asset: assets/fonts/neometric/Neometric-Regular.otf
          weight: 400
        - asset: assets/fonts/neometric/Neometric-AltRegular.otf
          weight: 400

        # Thin (Hairline) styles
        - asset: assets/fonts/neometric/Neometric-Hairline.otf
          weight: 100
        - asset: assets/fonts/neometric/Neometric-HairlineItalic.otf
          weight: 100
          style: italic

        # Extra Light styles
        - asset: assets/fonts/neometric/Neometric-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/neometric/Neometric-ExtraLightItalic.otf
          weight: 200
          style: italic

        # Light styles
        - asset: assets/fonts/neometric/Neometric-Light.otf
          weight: 300
        - asset: assets/fonts/neometric/Neometric-LightItalic.otf
          weight: 300
          style: italic

        # Medium styles
        - asset: assets/fonts/neometric/Neometric-Medium.otf
          weight: 500
        - asset: assets/fonts/neometric/Neometric-MediumItalic.otf
          weight: 500
          style: italic

        # Bold styles
        - asset: assets/fonts/neometric/Neometric-Bold.otf
          weight: 700
        - asset: assets/fonts/neometric/Neometric-BoldItalic.otf
          weight: 700
          style: italic

        # Extra Bold styles
        - asset: assets/fonts/neometric/Neometric-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/neometric/Neometric-ExtraBoldItalic.otf
          weight: 800
          style: italic

        # Black styles
        - asset: assets/fonts/neometric/Neometric-Black.otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric-BlackItalic.otf
          weight: 900
          style: italic

        # Heavy styles (Alternative Black)
        - asset: assets/fonts/neometric/Neometric-Heavy.otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric-HeavyItalic.otf
          weight: 900
          style: italic
