name: project_z
description: "Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Основные зависимости
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shop_domain:
    path: ../packages/shop_domain
  shop_hive:
    path: ../packages/shop_data/shop_hive
  shop_network:
    path: ../packages/shop_data/shop_network

  # Управление состоянием
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  provider: ^6.1.2

  # Навигация
  auto_route: ^9.3.0+1

  # UI компоненты
  flutter_svg: ^2.0.17
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  mask_text_input_formatter: ^2.9.0

  # Утилиты и инструменты
  fpdart: ^1.1.1
  equatable: ^2.0.7
  freezed: ^2.5.7
  logger: ^2.0.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  rxdart: ^0.28.0
  intl: any
  flutter_gen: ^5.10.0
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4

# Зависимости для разработки
dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: ^7.4.5
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  flutter_gen_runner: ^5.4.0

# Flutter конфигурация
flutter:
  uses-material-design: true
  generate: true

  # Ресурсы приложения
  assets:
    - assets/icons/
    - assets/icons/shared/
    - assets/icons/bottom_bar/
    - assets/icons/basket/
    - assets/icons/profile/
    - assets/icons/app_bar/
    - assets/icons/order/
    - assets/icons/search/
    - assets/l10n/
    - assets/img/
    - assets/img/basket/
    - assets/img/authentication/
    - assets/img/mock/
    - assets/img/footer/

  # Конфигурация шрифтов
  fonts:
    - family: Neometric
      fonts:
        # Regular styles
        - asset: assets/fonts/neometric/Neometric-Regular.otf
          weight: 400
        - asset: assets/fonts/neometric/Neometric-AltRegular.otf
          weight: 400

        # Thin (Hairline) styles
        - asset: assets/fonts/neometric/Neometric Hairline (Regular).otf
          weight: 100
        - asset: assets/fonts/neometric/Neometric Hairline Italic (Italic).otf
          weight: 100
          style: italic

        # Extra Light styles
        - asset: assets/fonts/neometric/Neometric Extra Light (Regular).otf
          weight: 200
        - asset: assets/fonts/neometric/Neometric Extra Light Italic (Italic).otf
          weight: 200
          style: italic

        # Light styles
        - asset: assets/fonts/neometric/Neometric Light (Regular).otf
          weight: 300
        - asset: assets/fonts/neometric/Neometric Light Italic (Italic).otf
          weight: 300
          style: italic

        # Medium styles
        - asset: assets/fonts/neometric/Neometric Medium (Regular).otf
          weight: 500
        - asset: assets/fonts/neometric/Neometric Medium Italic (Italic).otf
          weight: 500
          style: italic

        # Bold styles
        - asset: assets/fonts/neometric/Unnamed Bold (Regular).otf
          weight: 700
        - asset: assets/fonts/neometric/Neometric Bold Italic (Bold Italic).otf
          weight: 700
          style: italic

        # Extra Bold styles
        - asset: assets/fonts/neometric/Neometric Extra Bold (Bold).otf
          weight: 800
        - asset: assets/fonts/neometric/Neometric Extra Bold Italic (Bold Italic).otf
          weight: 800
          style: italic

        # Black styles
        - asset: assets/fonts/neometric/Neometric Black (Regular).otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric Black Italic (Bold Italic).otf
          weight: 900
          style: italic

        # Heavy styles (Alternative Black)
        - asset: assets/fonts/neometric/Neometric Heavy (Bold).otf
          weight: 900
        - asset: assets/fonts/neometric/Neometric Heavy Italic (Bold Italic).otf
          weight: 900
          style: italic

flutter_gen:
  output: lib/gen_assets/

  integrations:
    flutter_svg: true
