/// Flutter icons MyFlutterApp
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData time_left = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warranty = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verficate = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData error = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geo = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ready = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
