name: shop_network
description: "A new Flutter package project."
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  shop_domain:
    path: ../../shop_domain

  fpdart: ^1.1.1
  equatable: ^2.0.7
  dev: ^1.0.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  logger: ^2.0.1
  flutter_secure_storage: ^9.0.0
  money2: ^6.0.2
  intl: ^0.20.2

  #build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  injectable_generator: ^2.7.0
